const chart = {
  hospitalId: { type: String, hashKey: true },
  id: { type: String, rangeKey: true },
  type: String,
  date: { type: Date, index: { name: "date" } },
  fixed: Boolean,
  patient: { type: String, index: { name: "patient" } },
  txNames: { type: "list", list: [String] },
  content: {
    cc: {
      contents: [
        {
          teeth: { type: "list", list: [Number] },
          content: String,
          lastModifiedTime: Number
        }
      ],
      doctor: String,
      staff: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    },
    ma: {
      contents: [{ name: String, memo: String }],
      doctor: String,
      staff: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    },
    oe: [
      {
        id: String,
        teeth: { type: "list", list: [Number] },
        missings: { type: "list", list: [Number] },
        planes: Object,
        mode: String,
        target: String,
        content: String,
        icons: Object,
        doctor: String,
        staff: String,
        lastModifiedTime: Number,
        signature: {
          contents: String,
          status: String,
          staff: String
        },
        memo: String
      }
    ],
    tx: {
      date: {
        type: Date
      },
      price: Number,
      treatments: [
        {
          id: String,
          name: String,
          teeth: { type: "list", list: [Number] },
          diseases: [
            { id: String, code: String, content: String, diagnosis: String }
          ],
          doctor: String,
          staff: String,
          memo: String,
          images: { type: "list", list: [String] },
          treatBtns: [
            {
              id: String,
              category: String,
              name: String,
              fee: Number,
              folder: String,
              option: String,
              treatment: String,
              unit: String
            }
          ],
          treats: [
            {
              id: String,
              category: String,
              count: Number,
              price: Number,
              folder: String,
              name: String,
              option: String,
              unit: String,
              periodontal: [
                {
                  id: String,
                  updatedCount: Number,
                  values: [{ isBleed: Boolean, value: String }],
                  tooth: Number
                }
              ],
              cavity: [
                { tooth: Number, planes: { type: "list", list: [Number] } }
              ]
            }
          ],
          signature: {
            contents: String,
            status: String,
            staff: String
          },
          lastModifiedTime: Number
        }
      ]
    },
    di: {
      docissue: String,
      id: String,
      patient: String,
      category: String,
      deletable: Boolean,
      doctor: String,
      status: Number,
      signature: {
        contents: String,
        status: String,
        staff: String
      },
      data: {
        title: String,
        patientInfo: {
          name: String,
          age: String,
          sex: String,
          cellphoneNumber: String,
          phoneNumber: String,
          address: String,
          doctor: String
        },
        order: [
          {
            orderType: String,
            data: {
              question: String,
              list: [
                {
                  checked: Boolean,
                  text: String
                }
              ],
              answer: String,
              textData: String,
              title: String,
              description: String,
              date: Date,
              name: String,
              sign: { type: "list", list: [String] }
            }
          }
        ],
        ruType: String,
        ru2: {
          patientName: String,
          patientBirthdate: String,
          patientAddress: String,
          clinicName: String,
          doctorName: String,
          date: String,
          doctorSign: [String],
          patientSign: [String],
          clinicSign: [String]
        },

        ru3: {
          patientName: String,
          patientId: String,
          patientAddress: String,
          patientSign: [String],
          clinicName: String,
          clinicAddress: String,
          clinicPhoneNumber: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          date: String
        },

        ru4: {
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          patientName: String,
          patientId: String,
          patientAddress: String,
          clinicName: String,
          doctorName: String,
          doctorSign: [String],
          patientSign: [String],
          clinicSign: [String],
          date: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text17: String,
          text18: String,
          text19: String,
          text20: String,
          text21: String,
          text22: String,
          text23: String,
          text24: String,
          text25: String,
          text3_title1: String,
          text3_title1_1: String,
          text3_title1_2: String,
          text3_title1_3: String,
          text3_title1_4: String,
          text3_title1_5: String,
          text3_title2: String,
          text3_title2_1: String,
          text3_title2_2: String,
          text3_title2_3: String,
          text3_title2_4: String,
          text3_title2_5: String,
          text3_title3: String,
          text3_title3_1: String,
          text3_title3_2: String,
          text3_title3_3: String,
          text3_title3_4: String,
          text3_title3_5: String,
          text3_title4: String,
          text3_title4_1: String,
          text3_title4_2: String,
          text3_title4_3: String,
          text3_title4_4: String,
          text3_title4_5: String,
          text3_title5: String,
          text3_title5_1: String,
          text3_title5_2: String,
          text3_title5_3: String,
          text3_title5_4: String,
          text3_title5_5: String,
          text3_title6: String,
          text3_title6_1: String,
          text3_title6_2: String,
          text3_title6_3: String,
          text3_title6_4: String,
          text3_title6_5: String,
          text3_title7: String,
          text3_title7_1: String,
          text3_title7_2: String,
          text3_title7_3: String,
          text3_title7_4: String,
          text3_title7_5: String,
          text4_title1: String,
          text4_title1_1: String,
          text4_title1_2: String,
          text4_title1_3: String,
          text4_title1_4: String,
          text4_title1_5: String,
          text4_title2: String,
          text4_title2_1: String,
          text4_title2_2: String,
          text4_title2_3: String,
          text4_title2_4: String,
          text4_title2_5: String,
          text4_title3: String,
          text4_title3_1: String,
          text4_title3_2: String,
          text4_title3_3: String,
          text4_title3_4: String,
          text4_title3_5: String,
          text4_title4: String,
          text4_title4_1: String,
          text4_title4_2: String,
          text4_title4_3: String,
          text4_title4_4: String,
          text4_title4_5: String,
          text4_title5: String,
          text4_title5_1: String,
          text4_title5_2: String,
          text4_title5_3: String,
          text4_title5_4: String,
          text4_title5_5: String,
          text4_title6: String,
          text4_title6_1: String,
          text4_title6_2: String,
          text4_title6_3: String,
          text4_title6_4: String,
          text4_title6_5: String,
          text4_title7: String,
          text4_title7_1: String,
          text4_title7_2: String,
          text4_title7_3: String,
          text4_title7_4: String,
          text4_title7_5: String
        },
        ru5: {
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          patientName: String,
          patientId: String,
          patientAddress: String,
          patientBirthdate: String,
          clinicName: String,
          doctorName: String,
          doctorSign: [String],
          patientSign: [String],
          clinicSign: [String],
          date: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String
        },

        ru6: {
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          hhmmtt1: Number,
          hhmmtt2: Number,
          hhmmtt3: Number,
          hhmmtt4: Number,
          clinicName: String,
          clinicHomepage: String,
          clinicPhoneNumber: String,
          chiefDirector: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text17: String,
          text18: String,
          text19: String,
          text20: String,
          text21: String,
          text22: String,
          text23: String,
          text24: String
        },
        ru7: {
          patientId: String,
          patientName: String,
          patientAddress: String,
          patientBirthdate: String,
          doctorName: String,
          clinicName: String,
          clinicAddress: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          doctorSign: [String],
          patientSign: [String],
          clinicSign: [String],
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          table_1_1: String,
          table_1_2: String,
          table_1_3: String,
          table_1_4: String,
          table_2_1: String,
          table_2_2: String,
          table_2_3: String,
          table_2_4: String,
          table_3_1: String,
          table_3_2: String,
          table_3_3: String,
          table_3_4: String,
          table_4_1: String,
          table_4_2: String,
          table_4_3: String,
          table_4_4: String,
          table_5_1: String,
          table_5_2: String,
          table_5_3: String,
          table_5_4: String,
          table_6_1: String,
          table_6_2: String,
          table_6_3: String,
          table_6_4: String,
          table_text_1: String,
          table_text_2: String
        },

        ru8: {
          patientId: String,
          patientName: String,
          doctorName: String,
          clinicName: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          ddmmyyyy5: Number,
          doctorSign: [String],
          patientSign: [String],
          clinicSign: [String],
          date: Number,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text17: String,
          text18: String,
          text19: String,
          text20: String
        },

        ru9: {
          patientName: String,
          patientId: String,
          clinicName: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          ddmmyyyy5: Number,
          patientSign: [String],
          clinicSign: [String],
          date: Number,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text17: String,
          text18: String,
          text19: String,
          text20: String,
          text21: String,
          text22: String,
          text23: String,
          text24: String,
          text25: String,
          text26: String,
          text27: String,
          text28: String,
          text29: String
        },

        ru10: {
          patientName: String,
          clinicName: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          ddmmyyyy5: Number,
          patientSign: [String],
          clinicSign: [String],
          date: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text17: String,
          text_title1_1: String,
          text_title1_2: String,
          text_title1_3: String,
          text_title1_4: String,
          text_title2_1: String,
          text_title2_2: String,
          text_title2_3: String,
          text_title2_4: String,
          text_title3_1: String,
          text_title3_2: String,
          text_title3_3: String,
          text_title3_4: String,
          text_title4_1: String,
          text_title4_2: String,
          text_title4_3: String,
          text_title4_4: String,
          text_title5_1: String,
          text_title5_2: String,
          text_title5_3: String,
          text_title5_4: String,
          text_title6_1: String,
          text_title6_2: String,
          text_title6_3: String,
          text_title6_4: String,
          table_text1: String,
          table_text2: String
        },

        ru11: {
          patientName: String,
          patientBirthdate: String,
          patientAddress: String,
          patientId: String,
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String
        },

        ru12: {
          patientName: String,
          patientBirthdate: String,
          patientAddress: String,
          ddmmyyyy1: String,
          ddmmyyyy2: String,
          ddmmyyyy3: String,
          ddmmyyyy4: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String
        },

        ru13: {
          clinicName: String,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          lText1: String
        },

        ru14: {
          patientName: String,
          patientId: String,
          patientAddress: String,
          patientPhoneNumber: String,
          patientEmail: String,
          clinicAddress: String,
          clinicName: String,
          chiefDirector: String,
          patientSign: [String],
          chiefSign: [String],
          ddmmyyyy1: Number,
          ddmmyyyy2: Number,
          ddmmyyyy3: Number,
          ddmmyyyy4: Number,
          ddmmyyyy5: Number,
          ddmmyyyy6: Number,
          ddmmyyyy7: Number,
          ddmmyyyy8: Number,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          text18: String,
          text19: String,
          text20: String,
          text21: String,
          text22: String,
          text23: String,
          text24: String,
          text25: String,
          text26: String,
          text27: String,
          text28: String,
          text29: String,
          text30: String,
          text31: String,
          text32: String,
          text33: String,
          text34: String,
          text35: String
        },

        ru15: {
          ddmmyyyy1: Number,
          text1: String,
          text2: String,
          text3: String,
          text4: String,
          text5: String,
          text6: String,
          text7: String,
          text8: String,
          text9: String,
          text10: String,
          text11: String,
          text12: String,
          text13: String,
          text14: String,
          text15: String,
          text16: String,
          table_1_1: String,
          table_1_2: String,
          table_1_3: String,
          table_1_4: String,
          table_1_5: String,
          table_1_6: String,
          table_1_7: String,
          table_1_8: String,
          table_1_9: String,
          table_1_10: String,
          table_1_11: String,
          table_1_12: String,
          table_1_13: String,
          table_1_14: String,
          table_1_15: String,
          table_1_16: String,
          table_2_1: String,
          table_2_2: String,
          table_2_3: String,
          table_2_4: String,
          table_2_5: String,
          table_2_6: String,
          table_2_7: String,
          table_2_8: String,
          table_2_9: String,
          table_2_10: String,
          table_2_11: String,
          table_2_12: String,
          table_2_13: String,
          table_2_14: String,
          table_2_15: String,
          table_2_16: String,
          table_4_1: String,
          table_4_2: String,
          table_4_3: String,
          table_4_4: String,
          table_4_5: String,
          table_4_6: String,
          table_4_7: String,
          table_4_8: String,
          table_4_9: String,
          table_4_10: String,
          table_4_11: String,
          table_4_12: String,
          table_4_13: String,
          table_4_14: String,
          table_4_15: String,
          table_4_16: String,
          table_5_1: String,
          table_5_2: String,
          table_5_3: String,
          table_5_4: String,
          table_5_5: String,
          table_5_6: String,
          table_5_7: String,
          table_5_8: String,
          table_5_9: String,
          table_5_10: String,
          table_5_11: String,
          table_5_12: String,
          table_5_13: String,
          table_5_14: String,
          table_5_15: String,
          table_5_16: String
        },

        ru16: {
          doctorName: String,
          chiefDirector: String,
          text1: String,
          text2: String,
          text3: String,
          table_text1_1_1: String,
          table_text1_1_2: String,
          table_text1_1_3: String,
          table_text1_2_1: String,
          table_text1_2_2: String,
          table_text1_2_3: String,
          table_text1_3_1: String,
          table_text1_3_2: String,
          table_text1_3_3: String,
          table_text1_4_1: String,
          table_text1_4_2: String,
          table_text1_4_3: String,
          table_text1_5_1: String,
          table_text1_5_2: String,
          table_text1_5_3: String,
          table_text1_6_1: String,
          table_text1_6_2: String,
          table_text1_6_3: String,
          table_text1_7_1: String,
          table_text1_7_2: String,
          table_text1_7_3: String,
          table_text2_1_1: String,
          table_text2_1_2: String,
          table_text2_1_3: String,
          table_text2_2_1: String,
          table_text2_2_2: String,
          table_text2_2_3: String,
          table_text2_3_1: String,
          table_text2_3_2: String,
          table_text2_3_3: String,
          table_text2_4_1: String,
          table_text2_4_2: String,
          table_text2_4_3: String,
          table_text2_5_1: String,
          table_text2_5_2: String,
          table_text2_5_3: String,
          table_text2_6_1: String,
          table_text2_6_2: String,
          table_text2_6_3: String,
          table_text2_7_1: String,
          table_text2_7_2: String,
          table_text2_7_3: String
        },

        ru17: {
          text_1_1: String,
          text_1_2: String,
          text_1_3: String,
          text_2_1: String,
          text_2_2: String,
          text_2_3: String,
          text_3_1: String,
          text_3_2: String,
          text_3_3: String,
          text_4_1: String,
          text_4_2: String,
          text_4_3: String,
          text_5_1: String,
          text_5_2: String,
          text_5_3: String,
          text_6_1: String,
          text_6_2: String,
          text_6_3: String,
          text_7_1: String,
          text_7_2: String,
          text_7_3: String,
          text_8_1: String,
          text_8_2: String,
          text_8_3: String,
          text_9_1: String,
          text_9_2: String,
          text_9_3: String,
          text_10_1: String,
          text_10_2: String,
          text_10_3: String,
          text_11_1: String,
          text_11_2: String,
          text_11_3: String,
          text_12_1: String,
          text_12_2: String,
          text_12_3: String,
          text_13_1: String,
          text_13_2: String,
          text_13_3: String,
          text_14_1: String,
          text_14_2: String,
          text_14_3: String
        }
      }
    },
    pl: [
      {
        id: String,
        doctor: String,
        staff: String,
        status: String,
        memo: String,
        name: String,
        treatments: [
          {
            id: String,
            teeth: { type: "list", list: [Number] },
            memo: String,
            status: String,
            history: [
              {
                date: Number,
                category: String,
                price: Number,
                option: {
                  id: String,
                  content: String,
                  price: Number
                },
                memo: String,
                status: String
              }
            ],
            price: Number,
            payment: Number,
            content: {
              name: String,
              uuid: String,
              item: {
                name: String,
                unit: String,
                vat: Boolean,
                price: Number,
                useOption: Boolean,
                insurance: Boolean,
                option: {
                  id: String,
                  content: String,
                  price: Number
                }
              }
            },
            discount: {
              uuid: String,
              content: String,
              value: String,
              direct: Boolean,
              result: Number
            },
            lastModifiedTime: Number
          }
        ],
        lastModifiedTime: Number,
        signature: {
          contents: String,
          status: String,
          staff: String
        },
        fixed: Boolean
      }
    ],
    ps: {
      date: {
        type: Date
      },
      prescriptionNumber: String,
      doctor: String,
      patient: String,
      memo: String,
      diagnosis: [
        {
          id: String,
          code: String,
          content: String
        }
      ],
      medicines: [
        {
          name: String,
          form: String,
          dose: Number,
          times: Number,
          days: Number,
          usage: String
        }
      ],
      selectedBtn: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    },
    xr: {
      photoId: String,
      inspectionDate: Number,
      checkingDate: Number,
      doctor: String,
      filetype: String,
      opinion: [
        {
          contentText: String,
          resultText: String,
          selects: { type: "list", list: [Number] }
        }
      ]
    },
    mm: {
      images: { type: "list", list: [String] },
      text: String,
      doctor: String,
      staff: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    },
    pt: String, //TODO
    nx: {
      contents: [
        {
          teeth: { type: "list", list: [Number] },
          content: String,
          lastModifiedTime: Number
        }
      ],
      doctor: String,
      staff: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    },
    cn: {
      importantFactor: { type: "list", list: [String] },
      memo: String,
      result: String,
      doctor: String,
      staff: String,
      signature: {
        contents: String,
        status: String,
        staff: String
      }
    }
  },
  lastModifiedStaff: String,
  lastModifiedTime: Number,
  createTime: {
    type: Date,
    index: { name: "createTime" }
  }
};

export default chart;
