const claim = {
  hospitalId: { type: String, hashKey: true },
  id: { type: String, rangeKey: true },
  date: { type: Date, index: { name: "date" } },
  claimNumber: String,
  claimType: String,
  periodType: String,
  receiptNumber: String,
  claim: {
    claimFormatVersion: String,
    statementFormatVersion: String,
    formatNumber: String,
    nursingInstitutionNumber: String,
    receivingAgency: String,
    insuranceType: String,
    claimType: String,
    claimUnitType: String,
    treatmentType: String,
    treatmentAreaType: String,
    treatmentForm: String,
    treatmentDate: String,
    count: Number,
    totalMedicalCareCost1: Number,
    totalPersonalBurden: Number,
    totalPersonalBurdenExcess: Number,
    totalClaim: Number,
    totalSupport: Number,
    totalDisabled: Number,
    totalMedicalCareCost2: Number,
    totalCompensation: Number,
    totalPersonalBurden100: Number,
    totalCompensationPersonalBurden: Number,
    totalLessThan100: Number,
    totalLessThan100PersonalBurden: Number,
    totalLessThan100Claim: Number,
    totalLessThan100Compensation: Number,
    numCareDays: Number,
    numDoctors: Number,
    differentialIndex: String,
    differentialCharge: Number,
    claimDate: String,
    claimant: String,
    authorName: String,
    authorBirthDate: String,
    inspectionApprovalNumber: String,
    proxyClaimAgentCode: String,
    memo: String
  },
  breakdown: {
    chartNumber: String,
    general: {
      serialNumber: String,
      classification: String,
      formatNumber: String,
      nursingInstitutionNumber: String,
      guaranteedAgencyCode: String,
      medicalBenefitType: String,
      gongsangType: String,
      fixedRateType: String,
      claimCode: String,
      receiptNumber: String,
      serialNumber2: String,
      reasonCode: String,
      firstHospitalizedDate: String,
      memberName: String,
      certNumber: String,
      examineeName: String,
      examineeResidentRegistrationNumber: String,
      medicalCareBenefitDays: Number,
      hospitalizedDays: Number,
      hospitalizationPath: String,
      treatmentResult: String,
      medicalCareCost1: Number,
      personalBurden: Number,
      personalBurdenExcess: Number,
      claim: Number,
      support: Number,
      disabled: Number,
      daebul: Number,
      medicalCareCost2: Number,
      compensation: Number,
      personalBurden100: Number,
      compensationPersonalBurden: Number,
      lessThan100: Number,
      lessThan100PersonalBurden: Number,
      lessThan100Claim: Number,
      lessThan100Compensation: Number
    },
    diseases: [
      {
        serialNumber: String,
        classification: String,
        category: String,
        code: String,
        department: String,
        specializedDepartment: String,
        date: String,
        licenseNumber: String,
        licenseType: String,
        teeth: { type: "list", list: [Number] },
        koreanName: String,
        doctor: String
      }
    ],
    treatments: [
      {
        serialNumber: String,
        classification: String,
        hang: String,
        mok: String,
        lineNumber: Number,
        category: String,
        code: String,
        cost: String,
        oneDayDosingCount: Number,
        totalDosingDays: Number,
        oneTimeDosingAmount: String,
        price: Number,
        changeDate: String,
        licenseNumber: String,
        licenseType: String,
        teeth: { type: "list", list: [Number] },
        name: String,
        medicineUpperLimitPrice: Number,
        upperLimitPrice: Number,
        doctor: String
      }
    ],
    prescriptions: [
      {
        serialNumber: String,
        classification: String,
        prescriptionNumber: String,
        prescriptionDays: String,
        repeatPharmacyCount: String,
        lineNumber: Number,
        category: String,
        code: String,
        oneTimeDosingAmount: Number,
        oneDayDosingCount: Number,
        totalDosingDays: Number,
        personalBurdenCode: String
      }
    ],
    specifics: [
      {
        serialNumber: String,
        classification: String,
        unitType: String,
        prescriptionNumber: String,
        lineNumber: Number,
        code: String,
        desc: String
      }
    ]
  },
  transmitTime: Number,
  type: String,
  sendType: String,
  claimId: { type: String, index: { name: "claimId" } },
  createTime: {
    type: Date,
    index: { name: "createTime" }
  }
};

export default claim;
