const treat = {
  additionalCharge: Number,
  alternative: String,
  applicationDate: { type: Number, rangeKey: true },
  arbitrarilyPreparingProhibitedItem: String,
  billingSpecifications: String,
  calculateName: String,
  category: String,
  ceilingPrice: Number,
  classificationNumber: String,
  clinicPrice: Number,
  code: { type: String, hashKey: true },
  companyName: String,
  dentalHospitalPrice: Number,
  doseRoute: String,
  endDate: Number,
  englishName: String,
  exceptionalClassification: String,
  fixedPrice: String,
  healthagencyPrice: Number,
  hospitalPrice: Number,
  importOffice: String,
  insuranceType: String,
  isUserData: Boolean,
  lowPriceReplacingAdditionalCharge: String,
  mainIngredienCode: String,
  manufacturer: String,
  material: String,
  maternityClinicPrice: Number,
  medicalEquivalence: String,
  name: { type: String, index: { name: "name" } },
  nameWithConsonant: String,
  nameWithoutSpace: { type: String, index: { name: "nameWithoutSpace" } },
  note: String,
  note1: String,
  note2: String,
  noticeDate: String,
  operationStatus: Number,
  orientalMedicineHospitalPrice: Number,
  overlapApproval: String,
  payStandard: String,
  personalBurden30: String,
  personalBurden50: String,
  personalBurden80: String,
  personalBurdenRatio50: String,
  personalBurdenRatio80: String,
  personalBurdenRatio90: String,
  personalBurdenRatio100: String,
  preventExit: String,
  price: Number,
  productCodeAfter: String,
  productCodeBefore: String,
  professionalOrGeneral: String,
  rareClassification: String,
  relativeValueScore: Number,
  responseCode: String,
  scheduledSaleDate: String,
  selectedPayment: String,
  separation: String,
  sortation: Number,
  standard: String,
  type: { type: String, index: { name: "type" } },
  unit: String
};

export default treat;
